version: "3"
services:
  api:
    build: .
    restart: "on-failure"
    command: ["yarn", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VIRTUAL_HOST=api.syntaxer.localhost
    expose:
      - "3000"
  client:
    build: ../syntaxer
    restart: "on-failure"
    command: ["yarn", "run", "dev"]
    volumes:
      - ../syntaxer:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=syntaxer.localhost
      - API_HOST=http://api.syntaxer.localhost
    expose:
      - "8080"
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
