apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syntaxer-api
  labels:
    app: syntaxer-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: syntaxer-api
      tier: backend
  template:
    metadata:
      labels:
        app: syntaxer-api
        tier: backend
    spec:
      containers:
      - name: syntaxer-api
        image: us.gcr.io/syntaxer-182400/syntaxer-api:65f8a5b5f9ca2d37cee1f5cb814ad66276e747aa
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: syntaxer-api
  labels:
    app: syntaxer-api
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: node
  selector:
    app: syntaxer-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: syntaxer-api
  labels:
    app: syntaxer-api
    tier: backend
spec:
  rules:
  - host: syntaxer-api.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: syntaxer-api
          servicePort: 8080
