apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: backend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # image: us.gcr.io/syntaxer-182400/{{ .Chart.Name }}:65f8a5b5f9ca2d37cee1f5cb814ad66276e747aa
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
