apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "name" . }}
    tier: backend
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        tier: backend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # TODO(Will): Uncomment when moving to GCE
        # image: {{ .Values.registry.host }}/{{ .Values.registry.project }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.app.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.app.port }}
          initialDelaySeconds: 180
        readinessProbe:
          tcpSocket:
            port: {{ .Values.app.port }}
          initialDelaySeconds: 10
