apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: backend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # TODO(Will): Uncomment when moving to GCE
        # image: {{ .Values.registry.host }}/{{ .Values.registry.project }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
