apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "name" . }}
    tier: backend
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    name: node
  selector:
    app: {{ template "name" . }}
